language: python

services:
  - docker

install:
  - git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
  - export PATH=/tmp/bats-core/bin:$PATH
  - pip install gixy

script:
  - gixy ./files/etc/nginx/nginx.conf 
  - bats ./test
  - make build TAGNAME=$(printenv TRAVIS_BRANCH)
  - make run TAGNAME=$(printenv TRAVIS_BRANCH)
  - sleep 5
  - wget -q localhost:8080 -O- | grep -q "SOME-TEST-VARIABLE"

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      printenv DOCKERHUB_PASSWORD | docker login --username nstapelbroekbot --password-stdin;
      docker tag nstapelbroek/static-webserver:$TRAVIS_BRANCH docker.io/nstapelbroek/static-webserver:$TRAVIS_BRANCH;
      docker push docker.io/nstapelbroek/static-webserver;
    fi
